title: Link
description: 物换星移几度秋.
keywords: blog,css,html,php
show_downloads: false
show_comment: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://atlinker.cn" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

#install emoji
plugins:
  - jemoji

paginate: 8
paginate_path: "page:num"


# social
author: "Link"
image: 
twitter:
  username: 
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
